In [5]:
import torch

# Compute derivative using autograd

In [3]:
def f(x, y):
    return torch.sin(x * y) + torch.cos(x ** 2)

In [4]:
# Create input tensors x and y
x = torch.tensor(1.0, requires_grad=True)  # Example value for x
y = torch.tensor(2.0, requires_grad=True)  # Example value for y

# Compute the output tensor
output = f(x, y)

# Print the output tensor
print(output)

tensor(1.4496, grad_fn=<AddBackward0>)


In [5]:
output.backward()
print(x.grad)  # Gradient of output with respect to x
print(y.grad)

tensor(-2.5152)
tensor(-0.4161)


# Implementing class to compare fd bd central diffs

In [6]:
class example:
    def __init__(self, f, x, h: float = 1e-6):
        self.f = f
        self.x = x
        self.h = h

    def forward_diff(self):
        return (self.f(self.x + self.h) - self.f(self.x)) / self.h

    def backward_diff(self):
        return (self.f(self.x) - self.f(self.x - self.h)) / self.h

    def central_diff(self):
        return (self.f(self.x + self.h) - self.f(self.x - self.h)) / (2 * self.h)

In [7]:
def f(x):
    x = torch.tensor(x)
    return torch.exp(torch.exp(-x**2))

In [8]:
torch.rand(50) * 5

tensor([1.8567, 0.6372, 3.4412, 0.3307, 2.8430, 2.3237, 4.0820, 4.1412, 2.2694,
        0.5875, 1.4462, 4.3452, 2.9501, 2.5688, 0.6671, 3.6882, 0.6527, 4.1237,
        1.0818, 2.3111, 1.5546, 0.4184, 0.9880, 1.7064, 2.4011, 4.8785, 0.1089,
        2.4775, 3.8886, 0.9426, 2.5955, 0.9049, 4.1125, 0.7767, 4.2838, 3.8154,
        0.2914, 3.5013, 2.7409, 0.9425, 2.0893, 3.7448, 1.6546, 0.4735, 4.6990,
        3.8545, 0.7308, 4.5616, 2.6059, 3.9997])

In [9]:
fd_diff = []
bc_diff = []
cd_diff = []
for i in range(50):
  fd_diff.append(example(f, i, 0.01 ).forward_diff())
  bc_diff.append(example(f, i, 0.01 ).backward_diff())
  cd_diff.append(example(f, i, 0.01 ).central_diff())

In [10]:
fd_diff

[tensor(-0.0272),
 tensor(-1.0537),
 tensor(-0.0733),
 tensor(-0.0007),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.),
 tensor(0.)]

# Matrix normalization using broadcasting

In [6]:
import numpy as np

# Example 2D NumPy array of shape (n, m)
n = 4  # number of rows (vectors)
m = 3  # number of dimensions (features)
A = np.random.rand(n, m)

print("NumPy Array A:")
print(A)


NumPy Array A:
[[0.87199776 0.01586113 0.44489896]
 [0.95370927 0.11050986 0.250148  ]
 [0.78235819 0.44913626 0.90527212]
 [0.5131103  0.32396723 0.14395591]]


In [7]:
A_tensor = torch.tensor(A, dtype=torch.float32)

In [8]:
A_tensor.shape

torch.Size([4, 3])

In [9]:
row_norms_torch = torch.norm(A_tensor, dim=1, keepdim=True)

In [10]:
row_norms_torch.shape

torch.Size([4, 1])

In [11]:
C = A_tensor / row_norms_torch

In [12]:
C

tensor([[0.8906, 0.0162, 0.4544],
        [0.9613, 0.1114, 0.2521],
        [0.6122, 0.3514, 0.7083],
        [0.8227, 0.5195, 0.2308]])

In [13]:
row_norms_torch

tensor([[0.9791],
        [0.9921],
        [1.2780],
        [0.6237]])

In [14]:
A_tensor

tensor([[0.8720, 0.0159, 0.4449],
        [0.9537, 0.1105, 0.2501],
        [0.7824, 0.4491, 0.9053],
        [0.5131, 0.3240, 0.1440]])

# Pairwise Euclidean Distance Computation

In [15]:
C

tensor([[0.8906, 0.0162, 0.4544],
        [0.9613, 0.1114, 0.2521],
        [0.6122, 0.3514, 0.7083],
        [0.8227, 0.5195, 0.2308]])

In [16]:
C_expanded = C[:, None, :] - C[None, :, :]

In [17]:
C_expanded

tensor([[[ 0.0000,  0.0000,  0.0000],
         [-0.0706, -0.0952,  0.2023],
         [ 0.2785, -0.3352, -0.2539],
         [ 0.0679, -0.5033,  0.2236]],

        [[ 0.0706,  0.0952, -0.2023],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.3491, -0.2400, -0.4562],
         [ 0.1385, -0.4081,  0.0213]],

        [[-0.2785,  0.3352,  0.2539],
         [-0.3491,  0.2400,  0.4562],
         [ 0.0000,  0.0000,  0.0000],
         [-0.2106, -0.1680,  0.4775]],

        [[-0.0679,  0.5033, -0.2236],
         [-0.1385,  0.4081, -0.0213],
         [ 0.2106,  0.1680, -0.4775],
         [ 0.0000,  0.0000,  0.0000]]])

In [18]:
C[:, None, :]

tensor([[[0.8906, 0.0162, 0.4544]],

        [[0.9613, 0.1114, 0.2521]],

        [[0.6122, 0.3514, 0.7083]],

        [[0.8227, 0.5195, 0.2308]]])

In [19]:
C[None, :, :]

tensor([[[0.8906, 0.0162, 0.4544],
         [0.9613, 0.1114, 0.2521],
         [0.6122, 0.3514, 0.7083],
         [0.8227, 0.5195, 0.2308]]])

In [20]:
squared_diff = torch.sum(C_expanded ** 2, axis=2)

In [21]:
squared_diff

tensor([[0.0000, 0.0550, 0.2544, 0.3079],
        [0.0550, 0.0000, 0.3876, 0.1862],
        [0.2544, 0.3876, 0.0000, 0.3006],
        [0.3079, 0.1862, 0.3006, 0.0000]])